downloader_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('downloaderapp.urls'))
]

downloaderapp/urls.py
from django.urls import path
from .views import ytdl, igdl, ttdl,youtube_dl, yt_download_done, get_insta , decide

app_name = 'downloaderapp'
urlpatterns = [
    path('', ytdl, name='youtubeapp'),
    path('download/', youtube_dl, name='quality'),
    path('download/<resolution>/',yt_download_done,name='yt_done'),
    path('instagram/',igdl, name='instagramapp'),
    path('get_insta/',get_insta,name='get_insta'),
    path('tiktok/', ttdl, name='tiktokapp'),
    path('decide/',decide, name='decide')
]

downloaderapp/models.py
from django.db import models

# Create your models here.

downloaderapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from pytube import YouTube
from instalooter.looters import PostLooter
import os
from . import functions


def ytdl(request):
    return render(request, 'downloaderapp/youtube.html')

def youtube_dl(request):
    global url 
    url = request.GET.get('url')
    yt = YouTube(url)
    video = []
    video = yt.streams.filter(progressive=True).all()
    embed = url.replace("watch?v=", "embed/")
    return render(request, 'downloaderapp/ytdl.html',{'video': video, 'embed':embed})

def yt_download_done(request, resolution):
    global url
    homedir = os.path.expanduser('~')
    dirs = homedir + '/Downloads'
    print(dirs)
    if request.method == 'POST':
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request, 'downloaderapp/done.html')
    else:
        return render(request, 'downloaderapp/error.html')


def igdl(request):
    return render(request, 'downloaderapp/instagram.html')
 


def get_insta(request):
    link = request.POST.get('url')
    homedir = os.path.expanduser('~')
    dirs = homedir + '/Downloads'
    if request.method == 'POST':
        PostLooter(link).download(dirs)
        return render(request, 'downloaderapp/done.html')
    else:
        return render(request, 'downloaderapp/error.html')


def ttdl(request):
    return render(request, 'downloaderapp/tiktok.html')

def download(request,url):
    link = functions.downloader(url)
    return render(request, 'downloaderapp/tiktok.html', {"without_watermark": link})

def json(request,url):
    link = functions.downloader(url)
    return HttpResponse(link)

def decide(request):
    url = request.POST.get("url")
    return download(request,url)
  

downloaderapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'downloaderapp/style.css' %}">
    <link rel="icon" href="{% static 'downloaderapp/icb.ico' %}" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <!-- Navbar-->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a style="color: red;" class="navbar-brand" href="{% url 'downloaderapp:youtubeapp' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-youtube" viewBox="0 0 16 16">
            <path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/>
          </svg>  Youtube</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a style="color: darkmagenta;" class="nav-link" aria-current="page" href="{% url 'downloaderapp:instagramapp' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                  </svg>  Instagram</a>
              </li>
              <li class="nav-item">
                <a style="color: black;" class="nav-link " aria-current="page" href="{% url 'downloaderapp:tiktokapp' %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tiktok" viewBox="0 0 16 16">
                    <path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3V0Z"/>
                  </svg>  TikTok</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">About us</a>
              </li>

            </ul>
          </div>
        </div>
      </nav>

    <!--Content-->
        {% block content %}{% endblock %}
    </div>
    


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

downloaderapp/templates/downloaderapp/done.html
{%  extends 'base.html' %}

{% block title %}Download from Youtube{% endblock %}

{% block content%}
    <center><div class="alert alert-success" role="alert">
        Download is successfully!
      </div></center>
{% endblock %}

downloaderapp/templates/downloaderapp/error.html
{%  extends 'base.html' %}

{% block title %}Download from Youtube{% endblock %}

{% block content%}
    <center><div class="alert alert-danger" role="alert">
        Something wents wrong!
      </div></center>
{% endblock %}

downloaderapp/templates/downloaderapp/instagram.html
{%  extends 'base.html' %}

{% block title %}Download from Instagram{% endblock %}

{% block content%}

    <center><h1 style="color: darkmagenta;">Paste your Instagram video link below:</h1></center>
    <div class="container">
    <form action="{% url 'downloaderapp:get_insta' %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" style="color: darkmagenta;" class="form-label">Link: </label>
          <input name="url" type="text" class="form-control" id="link" aria-describedby="emailHelp">
        </div>
        <br>
        <center>
            <button class="btn btn-dark" style="background-color: darkmagenta;" type="submit">Download</button>
        </center>
      </form>
    </div>


{% endblock %}

downloaderapp/templates/downloaderapp/tiktok.html
{%  extends 'base.html' %}

{% block title %}Download from TikTok{% endblock %}

{% block content%}

    <center><h1 style="color: rgb(12, 126, 192);">Paste your Tik Tok video link below:</h1></center>
    <div class="container">
    <form action="{% url 'downloaderapp:decide' %}" method="get">
        <div class="mb-3">
          <label for="exampleInputEmail1" style="color: rgb(12, 126, 192);" class="form-label">Link: </label>
          <input name="url" type="text" class="form-control" id="link" aria-describedby="emailHelp">
          <input type="hidden" name="todo" value="1">
        </div>
        <br>
        <center><button type="submit" class="btn btn-primary">Download</button></center>
      </form>
    </div>


{% endblock %}

downloaderapp/templates/downloaderapp/youtube.html
{%  extends 'base.html' %}

{% block title %}Download from Youtube{% endblock %}

{% block content%}

    <center><h1 style="color: red;">Paste your Youtube video link below:</h1></center>
    <div class="container">
    <form action="download/" method="get">
        <div class="mb-3">
          <label for="exampleInputEmail1" style="color: red;" class="form-label">Link: </label>
          <input name="url" type="text" class="form-control" id="link" aria-describedby="emailHelp">
        </div>
        <br>
        <center><button type="submit" class="btn btn-danger">Download</button></center>
      </form>
    </div>


{% endblock %}

downloaderapp/templates/downloaderapp/ytdl.html
{%  extends 'base.html' %}

{% block title %}Download from Youtube{% endblock %}

{% block content%}
    <div class="container">
        <div class="ratio ratio-16x9">
            <iframe src={{embed}} title="YouTube video" allowfullscreen></iframe>
          </div>
    </div>
    <div class="container">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Size</th>
                <th scope="col">Resolution</th>
                <th scope="col">Type</th>
                <th scope="col">Download</th>
              </tr>
            </thead>
            {% for i in video %}
            <tbody>
              <tr>
                <th>{{i.filesize}}</th>
                <td>{{i.resolution}}</td>
                <td>{{i.type}}</td>
                <td>
                    <form action="{% url 'downloaderapp:yt_done' i.resolution %}" method="post">
                        {% csrf_token%}
                        <input type="submit" class="btn btn-success" value="Download">
                    </form>
                </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>      
    </div>


{% endblock %}